"""Rebuild structured reference files from the maintained specification below."""
from pathlib import Path
import json, re

ROOT = Path(__file__).resolve().parent

def component(id, name, coverage, evidence, anatomy, states, behavior, accessibility):
    return dict(id=id, name=name, coverage=coverage, evidence=evidence, anatomy=anatomy,
                states=states, behavior=behavior, accessibility=accessibility)

items = [
component('C01','App shell','Observed + HSE adaptation','E01 / E04 / E07',
 'Brand, primary destinations, catalog search, help, current context, account.',
 'Default, active destination, mobile navigation, loading context, access denied.',
 'HSE: use a 64px starting header, stable navigation and a visible organization/site context. Collapse navigation when it no longer fits.',
 'Skip link, navigation labels, one main region, aria-current on the active route; preserve focus after navigation.'),
component('C02','Mega menu and mobile navigation','Observed + HSE adaptation','E02 / E09',
 'Desktop grouped headings and links; mobile nested rows with chevrons, Back and Close.',
 'Closed, open, focused, expanded subsection, current destination.',
 'HSE: ordinary navigation links in desktop disclosure; full-width mobile modal; do not hide essential destinations in unlabelled icons.',
 'aria-expanded on disclosure, Escape closes, focus returns to opener. Mobile modal contains focus; navigation is not an ARIA application menu.'),
component('C03','Breadcrumbs','Observed + HSE adaptation','E12 / E15',
 'Ordered ancestor links, separators, current location.',
 'Full, collapsed ancestors, keyboard focused.',
 'HSE: readable path with current page as text; keep a meaningful parent on mobile and expose hidden ancestors.',
 'Label the navigation Breadcrumbs; separators decorative; current page aria-current=page.'),
component('C04','Search field and suggestions','Observed + HSE adaptation','E03 / E04',
 'Label, text input, clear action, submit, popup with suggestion types.',
 'Empty, entered, focused, suggestions, loading, no matches, request failure.',
 'HSE: 44px minimum / 48px touch, preserved query, labelled result types; keyboard Enter searches, Escape closes popup. Exact and suggested results are distinct.',
 'Combobox semantics only when implemented; listbox options, aria-expanded/controls/activedescendant; announce result changes politely.'),
component('C05','Filter toolbar and chips','Observed + HSE adaptation','E04 / E06 / E07',
 'Filter action with count, facet triggers, removable applied chips, Clear all, result count.',
 'Default, selected, open facet, focused, no results.',
 'HSE: keep count visible and wrap applied chips below the toolbar. An individual removal preserves all other filters.',
 'Removal buttons name the filter; do not nest buttons inside buttons; selection cannot depend on color alone.'),
component('C06','Filter drawer','Observed + HSE adaptation','E05 / E08',
 'Title, Close, scrollable fieldsets/accordions, count, Clear, Show results.',
 'Open, draft selection, applying, empty selection, error, dismissed.',
 'HSE: 360px desktop starting width / full viewport mobile. Stage changes and commit on Show results; Escape and Cancel discard drafts. This differs from observed Coursera immediate URL updates.',
 'Modal dialog name, initial focus, Tab containment, Escape, restore trigger. Clear inert/aria-hidden on every close path including in-flight updates.'),
component('C07','Buttons and action groups','Observed + HSE adaptation','E01 / E12',
 'Verb label, optional leading/trailing icon, optional pending indicator.',
 'Primary, secondary, tertiary, icon, destructive; default, hover, active, focus, disabled, loading.',
 'HSE: 44px default, 48px coarse pointer, 36px compact only for deliberate dense desktop contexts. One primary action per task group. Preserve button width during loading.',
 'Native button for mutation, anchor for navigation. Accessible name on icon actions. Visible focus. Disable duplicate submission and announce completion.'),
component('C08','Links and section navigation','Observed + HSE adaptation','E12 / E13',
 'Descriptive label; optional external-destination cue; current section indicator.',
 'Default, hover, focus, active location, visited where appropriate.',
 'HSE: underline inline links. Sticky section anchors scroll to content and respect header offset; they do not masquerade as tab panels.',
 'Accessible destination text; aria-current=location for current anchor. Keyboard focus cannot be covered by sticky bars.'),
component('C09','Catalog card','Observed + HSE adaptation','E04 / E07 / card geometry',
 'Optional image, owner, linked title, concise summary, duration/type, version, status.',
 'Default, hover, focus-within, saved, unavailable, image fallback.',
 'HSE: 16px corners/padding, 16:9 optional art, 14px metadata. Compact 64px image rows on mobile. Never truncate critical scope or restrictions.',
 'One primary linked title plus sibling actions. No nested interactive elements. Avoid redundant image alt when the same title is adjacent.'),
component('C10','Collections and pagination','Observed + HSE adaptation','E01 / E04',
 'Section title, result count, card list, optional See all / pagination controls.',
 'First/last page, current page, more loading, empty collection, error.',
 'HSE: use grids/lists for assigned work; reserve carousels for optional discovery. Keep query, filters, page and scroll position on Back.',
 'Label pagination and current page; expose list semantics; announce newly loaded range; all carousel content reachable without dragging.'),
component('C11','Course detail header','Observed + HSE adaptation','E12 / E15',
 'Breadcrumb, title, provider, outcomes, version, next action, scope.',
 'Available, assigned, in progress, unavailable, superseded version.',
 'HSE: 32/40px app title; 44/52 marketing display. Keep applicability/practical prerequisites near the main action; show the content version being used.',
 'One descriptive H1; logical heading sequence; long titles wrap; CTA is present in the meaningful document order.'),
component('C12','Summary facts','Observed + HSE adaptation','E12',
 'Label/value groups for duration, level, modules and outcome type.',
 'Known, unknown, not applicable, warning/blocking.',
 'HSE: use a definition list; stack on mobile. Replace consumer ratings with verified scope/version facts when those better support the task.',
 'Read label before value; explain unknowns; icons supplement text. Do not use unavailable values as zero.'),
component('C13','Tabs','Observed + HSE adaptation','E17',
 'Tablist, labelled tabs, active indicator, linked panel.',
 'Selected, unselected, keyboard focused, disabled if justified.',
 'HSE: Arrow keys/Home/End move focus; Enter/Space activates for manual tabs; activation and focus are distinct. My Learning showed manual-focus movement.',
 'tablist/tab/tabpanel, aria-selected, roving tabindex, aria-controls and aria-labelledby; only relevant panel is exposed.'),
component('C14','Accordion and syllabus','Observed + HSE adaptation','E13 / E14',
 'Heading trigger, summary/duration, chevron, content region, separate Preview/Start action.',
 'Collapsed, expanded, focus, locked content with reason.',
 'HSE: Enter/Space toggles; group related secondary details. Blocking prerequisites remain visible in the summary. Never nest Preview inside the expansion button.',
 'aria-expanded and aria-controls; meaningful headings and named region when useful; hide collapsed content from focus and accessibility.'),
component('C15','Text input and textarea','HSE extension; search input observed','E03 / R',
 'Visible label, optional helper, control, optional counter, inline error.',
 'Empty, filled, focus, read-only, disabled, invalid, pending save.',
 'HSE: 16px input text, 44px minimum; label above; preserve values after failure. Textarea grows or scrolls predictably.',
 'Label association, required semantics, aria-invalid and describedby for errors; errors explain recovery rather than color alone.'),
component('C16','Checkbox, radio, select and switch','Observed controls + HSE extension','E05 / E06',
 'Labelled options grouped by a legend; helper and optional count.',
 'Unchecked/checked, indeterminate checkbox, focus, disabled, invalid.',
 'HSE: checkbox for independent multiple choices; radio for one choice; select for long simple choices; switch only for immediate on/off settings. Label row is the hit target.',
 'Prefer native controls. Fieldset/legend, keyboard behavior, selected state announced; 44px label target. Counts are supplemental.'),
component('C17','Badges and qualification states','Observed badges + HSE extension','E04 / P01',
 'Explicit status text, optional icon, separate scope/expiry metadata.',
 'Not started, pending, complete, passed, authorized, expired, revoked, unknown.',
 'HSE: distinguish knowledge, site, practical, authorization and external credential milestones. All required gates must be met before authorization; missing data stays Unknown.',
 'Text is mandatory; distinguish states beyond hue. Do not make a noninteractive tag look like a clickable filter.'),
component('C18','Alerts and inline notices','Observed + HSE adaptation','E01 / E12a',
 'Severity icon, concise title, explanation, recovery/help link, optional Close.',
 'Information, success, warning, error; dismissible or persistent.',
 'HSE: place task errors near task. A blocking warning names the missing prerequisite. Dismissible informational notices must not hide critical unresolved status.',
 'role=alert only for urgent new failures; status/polite for routine updates. Visible title and text; close has an accessible name and target.'),
component('C19','Progress and assigned-learning card','HSE extension; populated Coursera card unverified','E17 / P01',
 'Assignment, due date, progress value, current module, next action, qualification status.',
 'Assigned, in progress, knowledge complete, blocked, overdue, stale save.',
 'HSE: exact progress value and last saved status; assigned work precedes discovery. Progress never authorizes a worker.',
 'Native progress or progressbar with accessible value/name; text alternative; no rapid live announcements for every percentage.'),
component('C20','Modal dialog','Observed + HSE adaptation','E05 / E08',
 'Title, message/content, Close, primary and cancel actions.',
 'Opening, open, busy, validation error, cancelled, closed.',
 'HSE: use native dialog or tested primitive; width fits viewport; retain content on validation error; destructive actions name the exact object/scope.',
 'Accessible name; modal focus containment; Escape; restore focus; background not interactive. Test with async content and route changes.'),
component('C21','Contextual rail and assistant','Observed + HSE adaptation','E12 / E12a',
 'Title, close/restore, supporting details or messages, citations, optional composer.',
 'Collapsed, expanded, loading, response, error, unavailable.',
 'HSE: collapsed by default; desktop rail only if main remains usable; mobile drawer. AI suggestions cannot approve evaluation or authorization.',
 'Nonmodal rail uses complementary landmark and does not trap focus. Label AI responses; updates polite; composer named; no unsolicited focus stealing.'),
component('C22','Data table and sorting','HSE extension; not observed','P01 / USWDS Table',
 'Caption, column headers, sort control, rows, scope/status, row action, pagination.',
 'Default, sorted ascending/descending, selected rows, loading, empty, error.',
 'HSE: use records table for comparisons; label bulk scope; preserve sorting/filter state; allow local horizontal scroll when relationships require it.',
 'Native table, th scope, aria-sort on sorted header, labelled region if scrollable. Avoid grid role without implementing its keyboard contract.'),
component('C23','Qualification requirements','HSE extension; not observed','P01',
 'Prerequisite label, state, evidence/version, responsible role, action, authorization summary.',
 'Not assessed, required, pending, satisfied, failed, not applicable, revoked.',
 'HSE: conditional requirement set from applicability model; show why blocked and who can resolve it. External credentials may satisfy a prerequisite; stages are not universally linear.',
 'List semantics; explicit status and next action; status changes announced after save. Do not hide reasons in hover-only tooltips.'),
component('C24','Evidence upload','HSE extension; not observed','P01',
 'File picker, requirements, file list, progress, per-file result, remove/replace.',
 'Idle, choosing, uploading, uploaded, validation error, network failure, cancelled.',
 'HSE: state accepted types/size before selection; preserve draft on failure; preview file association and version before submission.',
 'Keyboard-operable native file picker; drop area supplemental; accessible progress and per-file errors; no drag-only removal.'),
component('C25','Evaluation and signoff','HSE extension; not observed','P01',
 'Person/scope, rubric, evidence, evaluator, result, restrictions, review/submit.',
 'Draft, incomplete, ready for review, submitting, signed, rejected, superseded.',
 'HSE: explicit actor and scope; review consequential result; record server confirmation. Role enforcement is server-side, not inferred from enabled buttons.',
 'Grouped inputs, error summary, labels, preserved values. Confirmation communicates exact consequence. Never silently overwrite a signed record.'),
component('C26','Timeline and version record','HSE extension; not observed','P01',
 'Event, actor, timestamp with zone, object/version, reason, evidence link.',
 'Current, historical, superseded, correction, unavailable evidence.',
 'HSE: append historical events; show current versus version-at-training; stable export identifiers; show missing data explicitly.',
 'Ordered list with textual chronology; dates understandable without visual position; no color-only current-version indicator.'),
component('C27','Empty, no results and access denied','Observed empty + HSE extension','E16 / E17',
 'Contextual heading, explanation, permitted next action, optional illustration.',
 'First use, zero assignments, no matching filters, no permission, deleted/unavailable.',
 'HSE: distinguish absence from failed retrieval. No matches offers Clear filters; no assignments explains whether to browse or ask a supervisor.',
 'Announce updates in status; heading meaningful; recovery is keyboard reachable; decorative art has empty alt.'),
component('C28','Loading, failure, offline and conflict','HSE extension; not observed','R',
 'Stable content placeholder, state text, retry/reconnect/resolve action, last saved time.',
 'Initial loading, refreshing, partial failure, offline, stale, save conflict.',
 'HSE: preserve last known content with stale label; never show completion until server confirms. Retry must not duplicate submissions.',
 'aria-busy on relevant region; skeleton hidden from AT; one polite status; reduced motion; no indefinite spinner without recovery.'),
component('C29','Toast and save feedback','HSE extension; not observed','R',
 'Result text, optional Undo/View action, dismiss if useful.',
 'Success, pending, failure, expired message.',
 'HSE: status confirmation for low-risk saves; persistent error near the task. Toast cannot be the only evidence that qualification changed.',
 'Polite live region; do not move focus; important actions persist and are reachable; honor timing requirements.'),
component('C30','Tooltip, icon and provider identity','Observed + HSE adaptation','E04 / E10 / E12',
 'Consistent SVG icon; optional tooltip; provider name with supporting logo.',
 'Default, hover/focus tooltip, image fallback.',
 'HSE: 20px common icon, 16px metadata, 24px prominent; 1.5–2px consistent stroke recommendation. Provider name remains visible if image fails.',
 'Tooltip opens on focus too, Escape dismisses; supplementary content only. Decorative icons hidden; meaningful icon actions named.'),
component('C31','Learning player and assessment','HSE extension; not observed','P01',
 'Lesson region, outline, captions/transcript, progress, Back/Next, question/feedback/help.',
 'Ready, playing, paused, buffering, answered, correct/incorrect, saved, retry.',
 'HSE: support text-first instruction and human questions; exact assessment/version recorded; knowledge completion follows assessment and confirmed save rules.',
 'Keyboard controls and captions, no autoplay audio, visible focus, understandable assessment feedback; provide accessible timing alternatives.'),
component('C32','Footer and support','Observed + HSE adaptation','E14 / public footer DOM',
 'Support, accessibility, privacy, terms, contact, version/product identity.',
 'Desktop groups, mobile stacked groups, focused links.',
 'HSE: compact support footer on task screens; fuller navigation on acquisition pages; human help is reachable during learning.',
 'contentinfo landmark; descriptive links; logical reading order; do not force users through large link lists before core task content.')
]

(ROOT/'components.json').write_text(json.dumps(items,ensure_ascii=False,indent=2),encoding='utf-8')
css = (ROOT/'hse-tokens.css').read_text(encoding='utf-8')
tokens = dict(re.findall(r'(--hse-[\w-]+)\s*:\s*([^;]+);',css))
observed = {
 'provenance':'Computed styles in the live Coursera session; audit-assigned descriptive names, not official tokens.',
 'color':{'action':'#0056D2','text':'#0D0F12','muted':'#48546E','surface':'#FFFFFF','paleBlue':'#F0F6FF','border':'#C1CBDB','divider':'#DAE1ED','infoInverse':'#002457','inverseLink':'#87B8FF','focus':'#804EE4'},
 'typography':{'family':'"Source Sans Pro", Arial, sans-serif','detailDesktop':[44,52,600],'detailMobile':[32,40,600],'dashboardTitle':[24,28,600],'section':[20,24,600],'searchCardTitle':[16,20,600],'body':[16,24,400],'smallControl':[14,20,600],'metadata':[12,18,400]},
 'geometry':{'controlRadiusPx':8,'cardRadiusPx':16,'smallButtonHeightPx':36,'detailButtonHeightPx':48,'topicChipHeightPx':32,'filterTriggerHeightPx':36,'searchInputHeightPx':48,'desktopResultCardWidthPx':331.25,'desktopResultGapPx':12,'desktopResultMarginPx':32,'desktopContentMarginPx':48},
 'limitations':['No dark palette measured','No official breakpoint extraction','Hover/active/error token families not fully sampled','Detail with assistant rail has different geometry']}
(ROOT/'design-tokens.json').write_text(json.dumps({'version':'1.0','auditDate':'2026-09-07','timeZone':'America/New_York','courseraObserved':observed,'hseProposed':{'provenance':'Recommended HSE v1 values; see audit-report.md for rationale','cssCustomProperties':tokens,'breakpointsPx':[640,960,1280]}},indent=2),encoding='utf-8')

def lum(h):
    rgb=[int(h[i:i+2],16)/255 for i in (1,3,5)]
    vals=[x/12.92 if x<=.04045 else ((x+.055)/1.055)**2.4 for x in rgb]
    return sum(a*b for a,b in zip(vals,[.2126,.7152,.0722]))
def ratio(a,b):
    x,y=sorted([lum(a),lum(b)],reverse=True)
    return (x+.05)/(y+.05)
pairs=[('Coursera/HSE primary text','#0D0F12','#FFFFFF',4.5),('Coursera/HSE muted text','#48546E','#FFFFFF',4.5),('Coursera/HSE primary action','#FFFFFF','#0056D2',4.5),('Coursera card border — decorative only','#C1CBDB','#FFFFFF',3),('Coursera filter border — decorative only','#DAE1ED','#FFFFFF',3),('HSE control border','#687994','#FFFFFF',3),('HSE focus on white','#6B3AC7','#FFFFFF',3),('HSE focus on pale blue','#6B3AC7','#F0F6FF',3),('HSE info','#0048B1','#F0F6FF',4.5),('HSE success','#166534','#ECFDF3',4.5),('HSE warning','#854D0E','#FFF8E6',4.5),('HSE danger','#B42318','#FFF1F0',4.5),('HSE neutral badge','#48546E','#F2F5FA',4.5),('HSE action hover','#FFFFFF','#0048B1',4.5),('HSE action active','#FFFFFF','#003C94',4.5),('HSE destructive action','#FFFFFF','#B42318',4.5)]
contrast=[{'name':n,'foreground':a,'background':b,'ratio':ratio(a,b),'threshold':t,'passes':ratio(a,b)>=t} for n,a,b,t in pairs]
(ROOT/'contrast-results.json').write_text(json.dumps(contrast,indent=2),encoding='utf-8')

evidence=[
('E01','01-dashboard-desktop.png','https://www.coursera.org/','1440 × 1000','Recommendation region; cropped to omit personal greeting'),
('E02','02-mega-menu-desktop.png','https://www.coursera.org/search?query=occupational%20safety','1440 × 1000','Open desktop catalog mega menu; partial header frame'),
('E03','03-search-suggestions.png','https://www.coursera.org/search?query=occupational%20safety','1440 × 1000','Focused empty search with recent query, trending topics, and suggested courses'),
('E04','04-search-desktop.png','https://www.coursera.org/search?query=occupational%20safety','1440 × 1000','Unfiltered result grid'),
('E05','05-filter-dialog-desktop.png','https://www.coursera.org/search?query=occupational%20safety','1440 × 1000','Right filter drawer with Level expanded'),
('E06','06-filter-selected.png','https://www.coursera.org/search?query=occupational%20safety&productDifficultyLevel=Beginner&sortBy=BEST_MATCH','1440 × 1000','Selected Beginner checkbox and dynamic View count in desktop drawer'),
('E07','07-search-mobile.png','https://www.coursera.org/search?query=occupational%20safety&productDifficultyLevel=Beginner&sortBy=BEST_MATCH','390 × 844','Mobile search top and compact rows'),
('E08','08-filter-mobile.png','https://www.coursera.org/search?query=occupational%20safety&productDifficultyLevel=Beginner&sortBy=BEST_MATCH','390 × 844','Full-width mobile filter panel'),
('E09','09-navigation-mobile.png','https://www.coursera.org/search?query=occupational%20safety','390 × 844','Nested mobile category navigation with Back and Close controls'),
('E10','10-search-tablet.png','https://www.coursera.org/search?query=occupational%20safety&productDifficultyLevel=Beginner&sortBy=BEST_MATCH','768 × 1024','Two-column results; mobile-style navigation'),
('E11','11-search-320.png','https://www.coursera.org/search?query=occupational%20safety&productDifficultyLevel=Beginner&sortBy=BEST_MATCH','320 × 800','Narrow reflow; local chip strip'),
('E12','12-course-detail-desktop.png','https://www.coursera.org/learn/occupational-safety-and-health-administration-osha-basics','1440 × 1000','Course header with assistant rail closed'),
('E12a','12a-course-ai-panel.png','https://www.coursera.org/learn/occupational-safety-and-health-administration-osha-basics','1440 × 1000','Assistant rail expanded on arrival; no prompt sent'),
('E13','13-module-expanded.png','https://www.coursera.org/learn/occupational-safety-and-health-administration-osha-basics','1440 × 1000','First syllabus module expanded; sticky section navigation'),
('E14','14-faq-desktop.png','https://www.coursera.org/learn/occupational-safety-and-health-administration-osha-basics','1440 × 1000','First FAQ expanded'),
('E15','15-course-mobile.png','https://www.coursera.org/learn/occupational-safety-and-health-administration-osha-basics','390 × 844','Stacked course hero and full-width CTA'),
('E16','16-unmatched-query.png','https://www.coursera.org/search?query=zzqhseaudittestzzq','1440 × 1000','Single unmatched-query probe; broad results still shown'),
('E17','17-learning-empty.png','https://www.coursera.org/my-learning','1440 × 1000','Empty In Progress panel and tabs; personal heading cropped out')]
(ROOT/'evidence'/'index.json').write_text(json.dumps([dict(id=i,file=f,url=u,viewport=v,state=s) for i,f,u,v,s in evidence],indent=2),encoding='utf-8')
lines=['# Coursera evidence index','', 'Captured September 7, 2026, America/New_York. Browser already signed in; individual states can vary. Viewports below are CSS dimensions; cropped PNG dimensions differ. Retained screenshot content belongs to Coursera and its providers and is for attributed audit reference.','', '| ID | Screenshot | Source | Viewport | State |','|---|---|---|---|---|']
for i,f,u,v,s in evidence: lines.append(f'| {i} | [{f}]({f}) | [Coursera]({u}) | {v} | {s} |')
lines+=['','## Measurement and interaction records','','- [measurements.json](measurements.json): selected visible rendered elements; names/greetings excluded. Observed offscreen carousel content is not treated as viewport content.','- [card-geometry.json](card-geometry.json) and [card-container-geometry.json](card-container-geometry.json): DOM ancestry and CSS geometry of a result card.','- [dashboard-paint-summary.json](dashboard-paint-summary.json): rendered colors and radius frequencies; counts are sampling artifacts, not tokens.','- [filter-escape-observation.json](filter-escape-observation.json): first lingering aria-hidden/BODY-focus observation.','- [filter-escape-repeat.json](filter-escape-repeat.json): later successful dismissal restoring visible accessibility content and trigger focus. This limits the finding to intermittent behavior.','','## Keyboard tab observation','','My Learning: ArrowRight from In Progress focused Completed while In Progress remained selected (manual activation pattern). Focus outline measured rgb(128,78,228), 1px solid, 2px offset. No populated learning record was opened.']
(ROOT/'evidence'/'index.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')

print(f'Wrote {len(items)} components, {len(tokens)} HSE tokens, {len(evidence)} evidence entries, {len(contrast)} contrast checks.')
for c in contrast: print(f"{c['name']}: {c['ratio']:.3f}:1 {'PASS' if c['passes'] else 'LIMITATION'}")
